'use client';

import { useState } from 'react';
import Link from 'next/link';
import ReactMarkdown from 'react-markdown';
import { MOCK_LESSON } from '@/lib/mock-data';

const scoreMessage = (score: number, total: number) => {
  if (score === total) return 'Perfect score! 🎉';
  if (score === total - 1) return 'Excellent! ⭐';
  if (score === total - 2) return 'Good job! 👍';
  return 'Keep practicing 💪';
};

export default function ModuleOnePage() {
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [submitted, setSubmitted] = useState(false);

  const handleSelect = (questionIndex: number, optionIndex: number) => {
    if (submitted) return;
    setAnswers(prev => ({ ...prev, [questionIndex]: optionIndex }));
  };

  const handleSubmit = () => {
    setSubmitted(true);
  };

  const handleRetake = () => {
    setAnswers({});
    setSubmitted(false);
  };

  const totalQuestions = MOCK_LESSON.quiz.length;
  const score = MOCK_LESSON.quiz.reduce((acc, question, index) => {
    const answer = answers[index];
    return acc + (answer === question.answer_index ? 1 : 0);
  }, 0);
  const allAnswered = Object.keys(answers).length === totalQuestions;

  return (
    <main style={{ maxWidth: '760px', margin: '0 auto', padding: '0 24px 80px' }}>
      <section style={{ paddingTop: '40px' }}>
        <div style={{ fontSize: '13px', color: '#9CA3AF', lineHeight: 1.6 }}>
          Auto Course AI <span style={{ margin: '0 8px' }}>→</span> Prompt Engineering <span style={{ margin: '0 8px' }}>→</span> Module 1
        </div>

        <div style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', background: '#EEEDFE', color: '#534AB7', fontSize: '12px', fontWeight: 600, padding: '4px 12px', borderRadius: '999px', marginTop: '12px' }}>
          Module 1 of 4
        </div>

        <h1 style={{ fontSize: '36px', fontWeight: 800, color: '#0D0D0D', marginTop: '12px', letterSpacing: '-0.02em' }}>
          {MOCK_LESSON.title}
        </h1>

        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '16px', marginTop: '12px' }}>
          <span style={{ fontSize: '13px', color: '#6B7280' }}>⚡ Generated by 3 AI agents</span>
          <span style={{ fontSize: '13px', color: '#6B7280' }}>📚 7 sources cited</span>
          <span style={{ fontSize: '13px', color: '#6B7280' }}>⏱ 5 min read</span>
        </div>

        <div style={{ height: '2px', background: 'linear-gradient(90deg, #7F77DD, #1D9E75)', borderRadius: '2px', margin: '24px 0' }} />
      </section>

      <section>
        <div style={{ fontSize: '13px', fontWeight: 600, color: '#9CA3AF', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: '16px' }}>
          Lesson Content
        </div>
        <div className="prose">
          <ReactMarkdown>{MOCK_LESSON.lesson_markdown}</ReactMarkdown>
        </div>
      </section>

      <section style={{ background: '#EEEDFE', borderRadius: '16px', padding: '24px', marginTop: '40px', border: '1px solid #CECBF6' }}>
        <div style={{ fontSize: '13px', fontWeight: 700, color: '#534AB7', marginBottom: '12px' }}>
          🍳 Explained with a Cooking Analogy
        </div>
        <div style={{ fontSize: '16px', lineHeight: 1.75, color: '#3C3489' }}>
          {MOCK_LESSON.worked_example}
        </div>
      </section>

      <section>
        <h2 style={{ fontSize: '22px', fontWeight: 700, marginTop: '48px', marginBottom: '24px', color: '#0D0D0D' }}>
          Test Your Knowledge
        </h2>

        {MOCK_LESSON.quiz.map((question, questionIndex) => {
          const selected = answers[questionIndex];
          return (
            <div key={questionIndex} style={{ marginBottom: '28px' }}>
              <div style={{ display: 'flex', gap: '12px', alignItems: 'center', marginBottom: '12px' }}>
                <div style={{ width: '32px', height: '32px', background: '#EEEDFE', color: '#534AB7', fontSize: '12px', fontWeight: 700, borderRadius: '8px', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                  {String(questionIndex + 1).padStart(2, '0')}
                </div>
                <div style={{ fontSize: '16px', fontWeight: 600, color: '#0D0D0D', marginBottom: 0 }}>
                  {question.question}
                </div>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px' }}>
                {question.options.map((option, optionIndex) => {
                  const isSelected = selected === optionIndex;
                  const isCorrect = question.answer_index === optionIndex;
                  const showResult = submitted;

                  const optionStyle: React.CSSProperties = {
                    background: 'white',
                    border: '1.5px solid #E5E7EB',
                    borderRadius: '10px',
                    padding: '12px 16px',
                    fontSize: '14px',
                    cursor: showResult ? 'default' : 'pointer',
                    textAlign: 'left',
                    color: '#0D0D0D',
                  };

                  if (!showResult && isSelected) {
                    optionStyle.border = '1.5px solid #7F77DD';
                    optionStyle.background = '#EEEDFE';
                    optionStyle.color = '#3C3489';
                  }

                  if (showResult && isCorrect) {
                    optionStyle.background = '#E1F5EE';
                    optionStyle.border = '1.5px solid #1D9E75';
                    optionStyle.color = '#085041';
                  }

                  if (showResult && isSelected && !isCorrect) {
                    optionStyle.background = '#FEE2E2';
                    optionStyle.border = '1.5px solid #EF4444';
                    optionStyle.color = '#991B1B';
                  }

                  return (
                    <button
                      key={optionIndex}
                      type="button"
                      disabled={submitted}
                      onClick={() => handleSelect(questionIndex, optionIndex)}
                      style={optionStyle}
                    >
                      {option}
                    </button>
                  );
                })}
              </div>
            </div>
          );
        })}

        {!submitted && allAnswered && (
          <button type="button" className="gradient-btn" onClick={handleSubmit} style={{ marginTop: '24px', width: '100%' }}>
            Submit Quiz
          </button>
        )}

        {submitted && (
          <div style={{ marginTop: '32px', padding: '24px', borderRadius: '16px', border: '1px solid #E5E7EB', background: 'white' }}>
            <div style={{ fontSize: '48px', fontWeight: 800, color: '#7F77DD' }}>
              {score}/{totalQuestions}
            </div>
            <div style={{ fontSize: '16px', color: '#3C3489', marginTop: '12px' }}>
              {scoreMessage(score, totalQuestions)}
            </div>
            <button
              type="button"
              onClick={handleRetake}
              style={{
                marginTop: '20px',
                border: '1.5px solid #7F77DD',
                color: '#7F77DD',
                background: 'white',
                borderRadius: '10px',
                padding: '10px 24px',
                cursor: 'pointer',
              }}
            >
              Retake Quiz
            </button>
          </div>
        )}
      </section>

      <section>
        <h2 style={{ fontSize: '22px', fontWeight: 700, marginTop: '48px', marginBottom: '20px', color: '#0D0D0D' }}>
          Sources
        </h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          {MOCK_LESSON.citations.map((citation, index) => (
            <div key={citation.marker} style={{ display: 'flex', alignItems: 'flex-start', gap: '12px', padding: '14px 0', borderBottom: '1px solid #F5F5F5' }}>
              <div style={{ width: '32px', height: '32px', background: '#EEEDFE', color: '#534AB7', fontSize: '12px', fontWeight: 700, borderRadius: '8px', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                {citation.marker}
              </div>
              <div>
                <a href={citation.source_url} target="_blank" rel="noreferrer" style={{ color: '#7F77DD', fontWeight: 500, fontSize: '15px', textDecoration: 'none' }}>
                  {citation.source_title}
                </a>
                <div style={{ fontSize: '12px', color: '#9CA3AF', marginTop: '4px' }}>{citation.source_url}</div>
              </div>
            </div>
          ))}
        </div>
      </section>

      <footer style={{ display: 'flex', justifyContent: 'space-between', marginTop: '48px', paddingTop: '24px', borderTop: '1px solid #F5F5F5' }}>
        <Link href="/room/demo-room-001" style={{ color: '#7F77DD', fontSize: '14px', textDecoration: 'none' }}>
          ← Back to Agent Room
        </Link>
        <button type="button" className="gradient-btn" style={{ width: 'auto', padding: '12px 24px' }}>
          Start New Course →
        </button>
      </footer>
    </main>
  );
}
